### ISSUE TITLE
"node server" not working & getting this error

### ISSUE THREAD

**Issue by profoundhub** [profoundhub/FCC-Voting-App#86]
~/workspace (cloud) $ node server
/home/ubuntu/workspace/node_modules/connect-mongo/src/index.js:105
                throw new Error('Connection strategy not found');
                ^

Error: Connection strategy not found
    at MongoStore (/home/ubuntu/workspace/node_modules/connect-mongo/src/index.js:105:23)
    at Object.<anonymous> (/home/ubuntu/workspace/server.js:48:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by profoundhub** [comment]
using "npm start" works, using that now to build the app on c9

**Comment by profoundhub** [comment]
Any ideas why?

**Comment by SebastianLF** [comment]
#87

**Comment by profoundhub** [comment]
... :~/workspace (cloud) $ node start
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/workspace/start'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by profoundhub** [comment]
re: sync Daniel from Cloud #143 
Use "node webDevServer.c9.js" instead
